### PR TITLE
Merge main into dev/fast-interp

### PR DESCRIPTION
**Pull request by zhouwfang**
#46

### CODE REVIEW

**Review by ia0 — APPROVED** [review]
clean merge

**Comment by ia0** [comment]
I pushed the merge manually since the github is configured for squashing which would destroy history. Closing as done.

**Comment by zhouwfang** [comment]
By "manually", do you mean without a PR? Just wondering what/why history would be destroyed.

**Comment by ia0** [comment]
Yes, by pushing to the branch. I configured the repository to have linear history and using one commit per PR, so merge commits are impossible to do with a PR. I have to bypass the rules to push a merge commit, but this is fine for development branches. The whole development branch will eventually end up as a single commit in the main branch (as a PR).

The reason I want a merge commit, is that otherwise the history is rewritten, which means the next merge will be much more complicated and have a lot of conflicts. The correct way to use git is to merge, not squash. But linear history and squashing is much easier to understand. Since I'm not planning to have more than one long-term branch (namely `main`), using linear history and squashing has more benefits than issues.

**Pull request closed without merging**
